Initial commit

diff --git a/centos-yum-security b/centos-yum-security
--- a/centos-yum-security
+++ b/centos-yum-security
@@ -1,14 +1,24 @@
-# centos-yum-security
+#!/bin/bash
 
-Since the `yum --security` plugin does not work on CentOS, 
-this is a workaround for installing/querying security updates on CentOS 7.
+function yumInstall()
+{
+    # Install packages from $pkgFile
+    echo "Installing security updates..."
+    while read -r package; do
+        echo "Updating $package"
+        # Redirect stderr to stdout and filter out annoying warnings about
+        # deltarpms plus false positives about missing arguments
+        yum -q -y update "$package" 2>&1 | egrep -v '(delta|argument)'
+    done < "$pkgFile"
+    exit 0
+}
 
-Built around `centos-package-cron`:
-https://github.com/wied03/centos-package-cron
+this="centos-yum-security"
 
-## Usage and license(s):
-```
-centos-yum-security [-d] [-h] [-y]
+usage="$this [-d] [-h] [-y]"
+
+helptext="
+$(echo $usage)
 
 Emulate the yum --security plugin for CentOS 7.
 Basically a wrapper around 'centos-package-cron' (https://github.com/wied03/centos-package-cron)
@@ -26,10 +36,10 @@ Exit codes:
 100: Ok. Security updates available.
 0: Ok. (Clean exit)
 
-Author of centos-yum-security: 
+Author of $this: 
 Magnus Wallin <magnus.wallin@tutanota.com>
 
-License of centos-yum-security:
+License of $this:
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
@@ -55,7 +65,7 @@ following disclaimer.
 · Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the 
 following disclaimer in the documentation and/or other materials provided with the distribution.
 
-THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED 
+THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED 
 WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
 PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
@@ -63,65 +73,80 @@ PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR B
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF 
 SUCH DAMAGE.
-```
+"
 
-## Examples
-### Running, and installing updates:
-```
-sudo centos-yum-security
-Gathering information about packages needed for security. This will take a while...
-8 packages needed for security:
-dhclient-4.2.5-58.el7.centos.1
-dhcp-common-4.2.5-58.el7.centos.1
-dhcp-libs-4.2.5-58.el7.centos.1
-kernel-3.10.0-514.el7
-kernel-3.10.0-693.17.1.el7
-kernel-tools-3.10.0-693.17.1.el7
-kernel-tools-libs-3.10.0-693.17.1.el7
-python-perf-3.10.0-693.17.1.el7
-Install updates? [Y/N] y
-Installing security updates...
-Updating dhclient-4.2.5-58.el7.centos.1
-Updating dhcp-common-4.2.5-58.el7.centos.1
-Updating dhcp-libs-4.2.5-58.el7.centos.1
-Updating kernel-3.10.0-514.el7
-Updating kernel-3.10.0-693.17.1.el7
-Updating kernel-tools-3.10.0-693.17.1.el7
-Updating kernel-tools-libs-3.10.0-693.17.1.el7
-Updating python-perf-3.10.0-693.17.1.el7
-```
+dryRun=""
+assumeYes=""
 
-### Querying:
-```
-sudo centos-yum-security -d
-Gathering information about packages needed for security. This will take a while...
-73 packages needed for security:
-authconfig-6.2.8-14.el7
-bash-4.2.46-20.el7_2
-bind-libs-lite-9.9.4-37.el7
-bind-license-9.9.4-37.el7
-[. . .]
-vim-minimal-7.4.160-1.el7
-wpa_supplicant-2.0-20.el7
-```
+# Get command line args
+while getopts ":dhy" opt; do
+    case $opt in
+        d)
+            dryRun="true"
+            ;;
+        h)
+            echo "$helptext" | less
+            exit 0
+            ;;
+        y)
+            assumeYes="true"
+            ;;
+        *)
+            echo -e "Unknown option. '-d' and '-h' allowed. Usage:\n$usage"
+            exit 3
+            ;;
+    esac
+done
 
-## Installation:
-Apart from this script, you need to install `centos-package-cron` and its
-dependencies.
+shift $(($OPTIND-1))
 
-```
-yum install mailx yum-plugin-changelog wget
-```
+if ! which centos-package-cron &> /dev/null; then
+    echo "'centos-package-cron' not installed. 
+See: https://github.com/wied03/centos-package-cron for instructions"
+    exit 2
+fi
 
-Then check here for the latest `rpm`:
-https://github.com/wied03/centos-package-cron/releases
+# Need to be root
+if (( $EUID != 0 )); then
+    echo "You need to be root. Exiting"
+    exit 1
+fi
 
-Download the latest stable `rpm` using `wget`:
-```
-wget https://github.com/wied03/centos-package-cron/releases/download/releases/1.0.10/centos-package-cron-1.0-10.el7.centos.x86_64.rpm
-```
+# Save package information here
+pkgFile="/root/centos-sec-updates"
 
-Now install `centos-package-cron` and solve its dependencies:
-```
-sudo yum install centos-package-cron-1.0-10.el7.centos.x86_64.rpm
-```
+# Gather information about packages needed for security. Write to $pkgFile
+echo "Gathering information about packages needed for security. This will take a while..."
+centos-package-cron --output stdout --forceold | sed -nE '/.*http.*$/! s/^\* (.*$)/\1/p' | egrep -v '[MWTFS][a-z]{2} [FDJSNAOM][a-z]{2} ' | sort -u > "$pkgFile"
+
+# Check if we have content in $pkgFile
+packages=$(wc -l "$pkgFile" | awk '{ print $1 }')
+
+if (( "$packages" < 1 )); then
+    echo "No packages needed for security"
+    exit 50
+else
+    echo "$packages packages needed for security:"
+    cat "$pkgFile"
+    if [[ "$dryRun" == "true" ]]; then
+        exit 100
+    fi
+    if [[ "$assumeYes" == "true" ]]; then
+        yumInstall
+    fi
+fi
+
+while true; do
+    read -p "Install updates? [Y/N] " yn
+    case "$yn" in
+        [Yy])
+            yumInstall
+            ;;
+        [Nn])
+            echo "Aborting. List of packages saved in $pkgFile"
+            exit 100
+            ;;
+        *)
+            echo "Incorrect input."
+    esac
+done
